// import Navbar from "@/components/Layout/Navbar";
import "../globals.css";
import type { Metadata } from "next";
import { Epilogue } from "next/font/google";
import Image from "next/image";
// import Footer from "@/components/Layout/Footer";

const epilogue = Epilogue({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthRootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${epilogue.className} relative overflow-x-hidden`}>
        <main className="grid grid-cols-2">
          <div className="h-screen relative">
            <div className="h-full w-full absolute">
              <Image
                src={"/images/bg-auth.png"}
                alt="/images/bg-auth.png"
                fill
                objectFit="cover"
                objectPosition="bottom"
              />
            </div>
          </div>
          <div className="relative w-full">
            <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2">
              {children}
            </div>
          </div>
        </main>
      </body>
    </html>
  );
}
